### ISSUE TITLE
TVM and HalideIR circular dependency

### ISSUE THREAD

**Issue by doctaweeks** [dmlc/HalideIR#24]
It appears that as of cf6090aeaeb782d1daff54b0ca5c2c281d7008db it is no longer possible to separate HalideIR and TVM, otherwise there is an unresolved circular dependency. The two projects can only be built when combined in one tree thus it seems logical to merge the two code bases.

**Comment by tqchen** [comment]
This is true as a result of the recent node refactor. It is understandable to keep remove the circular dependency, we can move the node related things to HalideIR to keep it as an independent module.

**Comment by tqchen** [comment]
should be fixed by recent the recent change to master

**Comment by doctaweeks** [comment]
I don't know if you'd prefer this as a new issue but there is a collision resulting from this change. Both TVM and HalideIR try to install the header "tvm/runtime/node_base.h".

**Comment by tqchen** [comment]
This should be fixed by the recent master, which places node_base in a different place. The tvm still keeps a version of node_base for now mainly because the runtime system need to be relatively independent of node system. The file is likely going to be stable
